In [9]:
import pandas as pd
import glob
import warnings
warnings.filterwarnings('ignore')

In [27]:
stock_price_folder = "f:/huyle_data_projects/stock_price_prediction/data/for_pretrained_models/prices"
macro_folder = "f:/huyle_data_projects/stock_price_prediction/data/for_pretrained_models/macro"

In [56]:
stock_files = glob.glob(f"{stock_price_folder}/*.csv")
stock_list = []

for f in stock_files:
    df = pd.read_csv(f)
    df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%y')
    df = df[df['Date'] >= '2010-01-01'] # filter data from 2010 onwards
    stock_list.append(df)
combined_stocks = pd.concat(stock_list, ignore_index=True)


rename_map = {
    'DX-Y.NYB': 'dxy',
    'FEDFUNDS': 'fed_rate',
    'GC=F': 'gold',
    'CL=F': 'oil',
    '^GSPC': 'sp500'
}

macro_files = glob.glob(f"{macro_folder}/*.csv")
macro_list = []

for f in macro_files:
    df = pd.read_csv(f)
    df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%y')
    # df = df[df['Date'] >= '2010-01-04'] # filetr data from 04-01-2010 onwards to match the data from stock price files
    ticker = df['Ticker'].iloc[0]
    col_name = rename_map.get(ticker, ticker)
    df = df[['Date', 'Value']].rename(columns={'Value': col_name})
    df.set_index('Date', inplace=True)
    macro_list.append(df)

combined_macro = pd.concat(macro_list, axis=1).reset_index()
combined_macro = combined_macro.sort_values('Date').reset_index(drop=True)

## Combine stock describe

In [57]:
combined_stocks.head()

        Date  Open  High   Low  Close  Volume Ticker
0 2010-01-04  4.87  4.96  4.75   4.96  235620    FPT
1 2010-01-05  5.14  5.14  4.96   4.96  200040    FPT
2 2010-01-06  4.96  5.02  4.78   4.87   94870    FPT
3 2010-01-07  4.87  4.90  4.81   4.84  102720    FPT
4 2010-01-08  4.93  4.93  4.69   4.69  161560    FPT

In [64]:
combined_stocks.describe()

,Date,Open,High,Low,Close,Volume
count,24444,24444.000000,24444.000000,24444.000000,24444.000000,2.444400e+04
mean,2018-03-06 07:00:58.321060352,34.662541,35.086627,34.245019,34.658607,3.180511e+06
min,2010-01-04 00:00:00,0.600000,0.610000,0.590000,0.600000,0.000000e+00
25%,2014-02-10 00:00:00,8.880000,8.980000,8.770000,8.880000,3.002375e+05
50%,2018-03-08 12:00:00,26.890000,27.185000,26.505000,26.830000,8.897350e+05
75%,2022-04-04 00:00:00,55.790000,56.482500,55.080000,55.730000,2.410045e+06
max,2026-05-07 00:00:00,227.800000,231.000000,218.000000,225.500000,2.159991e+08
std,NaN,29.337491,29.751087,28.936113,29.329667,7.945223e+06

In [65]:
combined_stocks.isna().sum()

Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
Ticker    0
dtype: int64

In [58]:
combined_stocks.groupby('Ticker').Date.describe()

,count,mean,min,25%,50%,75%,max
Ticker,,,,,,,
FPT,4074,2018-03-06 07:00:58.321060352,2010-01-04 00:00:00,2014-02-10 06:00:00,2018-03-08 12:00:00,2022-04-03 06:00:00,2026-05-07 00:00:00
HPG,4074,2018-03-06 07:00:58.321060352,2010-01-04 00:00:00,2014-02-10 06:00:00,2018-03-08 12:00:00,2022-04-03 06:00:00,2026-05-07 00:00:00
MSN,4074,2018-03-06 07:00:58.321060352,2010-01-04 00:00:00,2014-02-10 06:00:00,2018-03-08 12:00:00,2022-04-03 06:00:00,2026-05-07 00:00:00
VCB,4074,2018-03-06 07:00:58.321060352,2010-01-04 00:00:00,2014-02-10 06:00:00,2018-03-08 12:00:00,2022-04-03 06:00:00,2026-05-07 00:00:00
VIC,4074,2018-03-06 07:00:58.321060352,2010-01-04 00:00:00,2014-02-10 06:00:00,2018-03-08 12:00:00,2022-04-03 06:00:00,2026-05-07 00:00:00
VNM,4074,2018-03-06 07:00:58.321060352,2010-01-04 00:00:00,2014-02-10 06:00:00,2018-03-08 12:00:00,2022-04-03 06:00:00,2026-05-07 00:00:00

## Combine macro describe

In [60]:
combined_macro.head()

        Date        dxy  fed_rate         gold        oil        sp500
0 2010-01-01        NaN      0.11          NaN        NaN          NaN
1 2010-01-04  77.529999       NaN  1117.699951  81.510002  1132.989990
2 2010-01-05  77.620003       NaN  1118.099976  81.769997  1136.520020
3 2010-01-06  77.489998       NaN  1135.900024  83.180000  1137.140015
4 2010-01-07  77.910004       NaN  1133.099976  82.660004  1141.689941

In [59]:
combined_macro.Date.describe()

count                             4184
mean     2018-03-06 02:50:21.797323008
min                2010-01-01 00:00:00
25%                2014-02-04 18:00:00
50%                2018-03-06 12:00:00
75%                2022-04-05 06:00:00
max                2026-05-06 00:00:00
Name: Date, dtype: object

In [61]:
combined_macro.describe()

,Date,dxy,fed_rate,gold,oil,sp500
count,4184,4111.000000,196.000000,4109.000000,4110.000000,4110.000000
mean,2018-03-06 02:50:21.797323008,92.855128,1.461122,1730.115355,71.724637,3027.211714
min,2010-01-01 00:00:00,72.930000,0.050000,1050.800049,-37.630001,1022.580017
25%,2014-02-04 18:00:00,82.655003,0.100000,1271.900024,55.109999,1836.559998
50%,2018-03-06 12:00:00,95.330002,0.350000,1529.300049,71.619999,2640.435059
75%,2022-04-05 06:00:00,99.180000,2.392500,1850.699951,88.617502,4141.384888
max,2026-05-06 00:00:00,114.110001,5.330000,5318.399902,123.699997,7365.120117
std,NaN,9.310940,1.822797,735.290707,20.769077,1579.188168

## Combine macro cleaning

In [72]:
cols_to_fill = ['dxy', 'fed_rate', 'gold', 'oil', 'sp500']
combined_macro[cols_to_fill] = combined_macro[cols_to_fill].ffill()

In [73]:
combined_macro.isna().sum(axis=0)

Date        0
dxy         1
fed_rate    0
gold        1
oil         1
sp500       1
dtype: int64

In [74]:
combined_macro.head()

        Date        dxy  fed_rate         gold        oil        sp500
0 2010-01-01        NaN      0.11          NaN        NaN          NaN
1 2010-01-04  77.529999      0.11  1117.699951  81.510002  1132.989990
2 2010-01-05  77.620003      0.11  1118.099976  81.769997  1136.520020
3 2010-01-06  77.489998      0.11  1135.900024  83.180000  1137.140015
4 2010-01-07  77.910004      0.11  1133.099976  82.660004  1141.689941

In [83]:
stock_price_output_path = "f:/huyle_data_projects/stock_price_prediction/data/for_pretrained_models/processed/stock_price.csv"
macro_output_path = "f:/huyle_data_projects/stock_price_prediction/data/for_pretrained_models/processed/macro.csv"

combined_stocks.to_csv(stock_price_output_path, index=False)
combined_macro.to_csv(macro_output_path, index=False)

## Join 2 dataframes

In [84]:
# merge using left join to keep vn trading days as the primary timeline
combined_df = pd.merge(combined_stocks, combined_macro, on='Date', how='left')

# ffill macro data within each ticker group to handle missing dates after merge
macro_cols = ['dxy', 'fed_rate', 'gold', 'oil', 'sp500']
combined_df[macro_cols] = combined_df.groupby('Ticker')[macro_cols].ffill()

combined_output_path = "f:/huyle_data_projects/stock_price_prediction/data/for_pretrained_models/processed/combined.csv"
combined_df.to_csv(combined_output_path, index=False)

## Get sample data

In [85]:
combined_stocks.groupby('Ticker').head(5).to_csv("f:/huyle_data_projects/stock_price_prediction/sample_data/sample_combined_stocks.csv", index=False)
combined_df.groupby('Ticker').head(5).to_csv("f:/huyle_data_projects/stock_price_prediction/sample_data/sample_combined_df.csv", index=False)
combined_macro.head(5).to_csv("f:/huyle_data_projects/stock_price_prediction/sample_data/sample_combined_macro.csv", index=False)